apiVersion: v1
kind: Service
metadata:
  name: my-ribbon-service
  namespace: consul-test  
  labels:
    component: my-ribbon-service
spec:
  type: NodePort
  selector:
    app: consul-ribbon-service
  ports:
    - name: service-port
      protocol: TCP
      port: 8308
      targetPort: 8308
      nodePort: 30183
