server:
  port: 8206
spring:
  application:
    name: consul-user-service
  cloud:
    consul: #Consul服务注册发现配置
      host: 192.168.31.200
      port: 30083
      discovery:
        service-name: ${spring.application.name}
